### PR TITLE
disabling offset calc, when shadows (or mirror mod) are rendering

### PR DESCRIPTION
**Pull request by KosmX**
Lock body when rendering shadow or immersive portals mod.
I haven't found a boolean button...

### CODE REVIEW

**Comment by tr7zw** [comment]
To be honest I don't see any difference that this makes? The shadow is a bit offset compared to the body location because the body gets offset behind the camera. Also seems to work with the Immersive portals mod?

**Comment by KosmX** [comment]
**Using immersive portals' mirror:**

without modify it (max offset)



with modification:



Of course, offset modification will be disabled if first-person model is turned off.

**Comment by KosmX** [comment]
sometimes it was annoying to see my shadow moving...

**Comment by tr7zw** [comment]
Ah ok, I wasn't aware that there's mirror. Gonna check it, probably try to replace the int with a boolean and then this should be fine.

**Comment by KosmX** [comment]
I'm just a beginner programmer (before university) and I don't know, how to do that...

**Pull request merged**
